{
 "title": "Synthetic Monitoring Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Coach Score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sitespeed.summary.www_vila_app_br.*.*.coach.score.median"
    }
   ]
  },
  {
   "title": "Performance score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sitespeed.summary.www_vila_app_br.*.*.coach.performance.score.median"
    }
   ]
  },
  {
   "title": "Best practices score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sitespeed.summary.www_vila_app_br.*.*.coach.bestpractice.score.median"
    }
   ]
  },
  {
   "title": "Privacy score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sitespeed.summary.www_vila_app_br.*.*.coach.privacy.score.median"
    }
   ]
  },
  { "title": "Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "DNS Lookup Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.www_vila_app_br.*.*.browsertime.pageTimings.domainLookupTime.mean"
    }
   ]
  },
  {
   "title": "TCP Connection Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.www_vila_app_br.*.*.browsertime.pageTimings.serverConnectionTime.mean"
    }
   ]
  },
  {
   "title": "Redirect Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.www_vila_app_br.*.*.browsertime.pageTimings.redirectionTime.mean"
    }
   ]
  },
  {
   "title": "First Paint Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.www_vila_app_br.*.*.browsertime.firstPaint.mean"
    }
   ]
  },
  {
   "title": "DOM Interactive Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.www_vila_app_br.*.*.browsertime.pageTimings.domInteractiveTime.mean"
    }
   ]
  },
  {
   "title": "DOM Content Loaded Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.www_vila_app_br.*.*.browsertime.pageTimings.domContentLoadedTime.mean"
    }
   ]
  },
  {
   "title": "Download Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.www_vila_app_br.*.*.browsertime.pageTimings.pageDownloadTime.mean"
    }
   ]
  },
  {
   "title": "Fully Loaded Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.www_vila_app_br.*.*.browsertime.pageTimings.pageLoadTime.mean"
    }
   ]
  },
  {
   "title": "Visual render complete",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.www_vila_app_br.*.*.browsertime.visualMetrics.VisualComplete99.mean"
    }
   ]
  }
 ]
}