{
 "title": "Akamai Observability",
 "time": { "from": "now-6h", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "AND_statusCode", "query": "include : IN, exclude : NOT IN" },
   {
    "name": "statusCode",
    "label": "HTTP Status Code",
    "query": "200,201,202,204,205,206,301,302,304,307,308,400,401,403,404,405,406,408,409,410,411,412,413,414,415,416,417,421,425,428,429,431,451,500,501,502,503,504,505,506,511"
   },
   { "name": "AND_cacheStatus", "query": "include : IN, exclude : NOT IN" },
   { "name": "cacheStatus", "label": "Cache Status", "query": "true : 1, false : 0" },
   { "name": "AND_reqHost", "query": "include : IN, exclude : NOT IN" },
   {
    "name": "reqHost",
    "label": "Hostname",
    "query": "SELECT arrayJoin(topK(50)(reqHost)) FROM ${table} WHERE $__timeFilter(reqTimeSec)"
   },
   { "name": "AND_reqMethod", "query": "include : IN, exclude : NOT IN" },
   {
    "name": "reqMethod",
    "label": "Method",
    "query": "SELECT arrayJoin(topK(50)(reqMethod)) FROM ${table} WHERE $__timeFilter(reqTimeSec)"
   },
   { "name": "AND_rspContentType", "query": "include : IN, exclude : NOT IN" },
   {
    "name": "rspContentType",
    "label": "Content Type",
    "query": "SELECT arrayJoin(topK(50)(rspContentType)) FROM ${table} WHERE $__timeFilter(reqTimeSec)"
   },
   { "name": "AND_errorCode", "query": "include : IN, exclude : NOT IN" },
   {
    "name": "errorCode",
    "label": "Error Code",
    "query": "SELECT arrayJoin(topK(50)(errorCode)) FROM ${table} WHERE $__timeFilter(reqTimeSec)"
   },
   { "name": "edge_response_time_percentile", "label": "Edge Response Time Percentile", "query": "0.5 , 0.75 , 0.90 , 0.95, 0.99" },
   { "name": "AND_reqPath", "query": "include : IN, exclude : NOT IN" },
   { "name": "reqPath", "label": "Path" },
   { "name": "AND_cliIP", "query": "include : IN, exclude : NOT IN" },
   { "name": "cliIP", "label": "Client IP" },
   { "name": "AND_country", "query": "include : IN, exclude : NOT IN" },
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT arrayJoin(topK(50)(country)) FROM ${table} WHERE $__timeFilter(reqTimeSec)"
   },
   {
    "name": "transferTimeMSec_percentile",
    "query": "$__conditionalAll(SELECT quantile(${edge_response_time_percentile})(transferTimeMSec) FROM ${table} WHERE $__timeFilter(reqTimeSec),$edge_response_time_percentile)"
   },
   {
    "name": "metric_name",
    "label": "Filter on Metric",
    "query": "SELECT name\nFROM system.columns\nWHERE database = splitByChar('.', '${table}')[1]\nAND table = splitByChar('.', '${table}')[2]\nAND type IN ('Nullable(UInt8)', 'Nullable(UInt16)', 'Nullable(UInt32)', 'Nullable(UInt64)', 'Nullable(Int8)', 'Nullable(Int16)', 'Nullable(Int32)', 'Nullable(Int64)', 'UInt8', 'UInt16', 'UInt32', 'UInt64', 'Int8', 'Int16', 'Int32', 'Int64', 'Float', 'Nullable(Float)')"
   },
   { "name": "metric_filter", "query": "<,>, <=, >=,=" },
   { "name": "metric_value" },
   { "name": "table", "query": "hydrolix_demo.ds2" },
   {
    "name": "catalog",
    "query": "SELECT concat(project,'.`',table,'#.catalog`')\nFROM (SELECT splitByChar('.','${table}')[1] as project, splitByChar('.','${table}')[2] as table)"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Akamai Time",
     "type": "timeseries",
     "description": "The time in milliseconds from when the edge server is ready to send the first byte of the response to when the last byte reaches the kernel.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\nquantile(0.25)(transferTimeMSec) as 25th,\nquantile(0.5)(transferTimeMSec) as 50th,\nquantile(0.75)(transferTimeMSec) as 75th,\nquantile(0.9)(transferTimeMSec) as 90th,\nquantile(0.95)(transferTimeMSec) as 95th,\nquantile(0.99)(transferTimeMSec) as 99th\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60"
      }
     ]
    },
    {
     "title": "Application Time",
     "type": "timeseries",
     "description": "The time in milliseconds from when the edge server receives the last byte of the request to when it sends the first bytes of the response.\n",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\nquantile(0.25)(turnAroundTimeMSec) as 25th,\nquantile(0.5)(turnAroundTimeMSec) as 50th,\nquantile(0.75)(turnAroundTimeMSec) as 75th,\nquantile(0.9)(turnAroundTimeMSec) as 90th,\nquantile(0.95)(turnAroundTimeMSec) as 95th,\nquantile(0.99)(turnAroundTimeMSec) as 99th\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60"
      }
     ]
    }
   ]
  },
  { "title": "Requests / Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Hits per Response Code",
   "type": "timeseries",
   "description": "Number of request group by Response Code",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT toString(statusCode) as HTTP_Status_Code, $__timeInterval(reqTimeSec) as time, count(*) as code\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nGROUP BY HTTP_Status_Code, time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60"
    }
   ]
  },
  {
   "title": "Hits per Akamai Error Code",
   "type": "timeseries",
   "description": "Number of request group by HTTP Status Code",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT toString(errorCode) as Error_Code, $__timeInterval(reqTimeSec) as time, count(*) as error\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nand errorCode is not NULL\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nGROUP BY Error_Code, time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60"
    }
   ]
  },
  {
   "title": "Bytes Delivered",
   "type": "timeseries",
   "description": "Sum of Total Bytes Delivered",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\nsum(totalBytes) as Bytes_Delivered\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60"
    }
   ]
  },
  {
   "title": "Hits Per Content Type",
   "type": "piechart",
   "description": "Number of requests group by Content Type",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ncount(),\nrspContentType\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND rspContentType IS not NULL\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nGROUP BY rspContentType ORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "description": "Cache Hit Ratio :\nsum of all request with cacheStatus: 1 / divided by total count of request",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT time, cache_hit FROM(\nSELECT $__timeInterval(reqTimeSec) as time,\nsumIf(cacheStatus,1) as \"cached\",\ncached/count() * 100 as \"cache_hit\"\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nGROUP BY time ORDER BY time)\nSETTINGS hdx_query_max_execution_time=60"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Throughput is the sum of all bytes delivered / divided by sum of transfert time",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\nsum(totalBytes) / sum(transferTimeMSec/1000) as throughput\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60"
    }
   ]
  },
  {
   "title": "Top 50 Hostnames",
   "type": "table",
   "description": "Number of requests group by Hostname",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(reqHost)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\n    ) AS top_50_reqHost\nSELECT\n    count(),\n    reqHost\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_reqHost, reqHost)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nGROUP BY reqHost\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60"
    }
   ]
  },
  {
   "title": "Top 50 Path",
   "type": "table",
   "description": "Number of requests group by Path",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(reqPath)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\n    ) AS top_50_reqPath\nSELECT\n    count(),\n    reqPath\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_reqPath, reqPath)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nGROUP BY reqPath\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60"
    }
   ]
  },
  {
   "title": "Top 50 Referer",
   "type": "table",
   "description": "Number of requests group by Referer",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(referer)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\n    ) AS top_50_referer\nSELECT\n    count(),\n    decodeURLComponent(referer) as referer\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_referer, referer)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nGROUP BY referer\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60"
    }
   ]
  },
  {
   "title": "Top 50 User Agent",
   "type": "table",
   "description": "Number of requests group by User Agent",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(UA)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\n    ) AS top_50_UA\nSELECT\n    count(),\n    decodeURLComponent(UA) as userAgent\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_UA, UA)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nGROUP BY userAgent\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60"
    }
   ]
  },
  {
   "title": "Top 50 IP",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(cliIP)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\n    ) AS top_50_cliIP\nSELECT\n    count(),\n    cliIP\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_cliIP, cliIP)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nGROUP BY cliIP\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60"
    }
   ]
  },
  {
   "title": "Top 50 Countries",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(country)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\n    ) AS top_50_country\nSELECT\n    count(),\n    country\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_country, country)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nGROUP BY country\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60"
    }
   ]
  },
  {
   "title": "Top 50 Cities",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(city)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\n    ) AS top_50_city\nSELECT\n    count(),\n    city\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_city, city)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nGROUP BY city\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60"
    }
   ]
  }
 ]
}