{
 "title": "Synthetic Monitoring Overview",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Coach Score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sitespeed.summary.*.*.*.coach.score.median"
    }
   ]
  },
  {
   "title": "Performance score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sitespeed.summary.*.*.*.coach.performance.score.median"
    }
   ]
  },
  {
   "title": "Best practices score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sitespeed.summary.*.*.*.coach.bestpractice.score.median"
    }
   ]
  },
  {
   "title": "Privacy score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sitespeed.summary.*.*.*.coach.privacy.score.median"
    }
   ]
  },
  { "title": "Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "DNS Lookup Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.*.*.*.browsertime.pageTimings.domainLookupTime.*"
    }
   ]
  },
  {
   "title": "TCP Connection Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.*.*.*.browsertime.pageTimings.serverConnectionTime.*"
    }
   ]
  },
  {
   "title": "Redirect Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.*.*.*.browsertime.pageTimings.redirectionTime.*"
    }
   ]
  },
  {
   "title": "First Paint Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.*.*.*.browsertime.firstPaint.*"
    }
   ]
  },
  {
   "title": "DOM Interactive Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.*.*.*.browsertime.pageTimings.domInteractiveTime.*"
    }
   ]
  },
  {
   "title": "DOM Content Loaded Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.*.*.*.browsertime.pageTimings.domContentLoadedTime.*"
    }
   ]
  },
  {
   "title": "Download Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.*.*.*.browsertime.pageTimings.pageDownloadTime.*"
    }
   ]
  },
  {
   "title": "Visual render complete",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.*.*.*.browsertime.visualMetrics.*.*"
    }
   ]
  },
  {
   "title": "Fully Loaded Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sitespeed.summary.*.*.*.browsertime.pageTimings.pageLoadTime.*"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Content Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "sitespeed.pageSummary.*.*.*.*.pagexray.contentTypes.*.requests"
    }
   ]
  },
  {
   "title": "Content Size",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "sitespeed.pageSummary.*.*.*.*.pagexray.contentTypes.*.contentSize"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "sitespeed.pageSummary.*.*.*.*.pagexray.responseCodes.*"
    }
   ]
  }
 ]
}